PingCAP-QE/devops-config

tidb/verify.yaml
=> fix yaml format

tidb/verify.yaml
- change yaml format Camel-Case
=> change yaml format Camel-Case

tiem/verify.yaml
=> tiem: cyclo config

tiem/verify.yaml
move verify scripts to project repo to make the verify config file simple
=> simplify the steps

tiem/verify.yaml
=> gosec: add gosec config

tiem/verify.yaml
*  make cyclo & gosec not block ci
=> cmd alway true, not block ci

tidb/verify.yaml, tiem/verify.yaml
=> reformat yaml

parser/verify.yaml
=> parser: add parser ci

tidb/verify.yaml
=> add tidb cyclo and gosec ci

pd/verify.yaml
* add pd verify ci config 
* only contains go security check and cyclo check
=> pd: add pd ci config

tidb/verify.yaml
* make gosec check alway success, not block ci
=> tidb: make gosec not block ci

dbaas-docs/merge.yaml, dev-guide/merge.yaml, docs-dm/merge.yaml, docs-tidb-operator/merge.yaml, docs/merge.yaml
add build PDF scripts for the reset docs repo
@dianqihanwangzi  PTAL
=> chore: add build PDF scripts

tidb/daily.yaml
=> modify tidb daily  ci

pd/verify.yaml, tidb/daily.yaml, tidb/verify.yaml, tiem/verify.yaml
* output cyclo log to file for analyse
=> cyclo: tee cyclo log to file for analyse

tiem/verify.yaml
Problem Summary: modify build and test task for tiem
What's Changed:
modify tiem/verify.yaml file and modiy build and test task
How it works:
Just to use "make" command to build this project, use "make ci_test" command to run unit-test
=> tiem: modify make build and make test for tiem

tiem/verify.yaml
Problem Summary: solve "make lint" problems
What's Changed:
Modify verify.yaml for lint task
How it works:
=> tiem: modify make lint task

tidb/daily.yaml
- add ut cov and lint for tidb
=> add ut cov and lint for tidb

docs-cn/verify.yaml, docs/verify.yaml
update docs build env(add ssh private key)
=> update docs build env(add ssh private key)

ticdc/verify.yaml
=> cdc: incr resources limit

tidb/daily.yaml
=> feat: add notify config

tidb/daily.yaml
* default ref is string, default is master
=> adjust default ref to single string

ticdc/verify.yaml
=> ticdc and dm add codecov token

tidb/daily.yaml
=> add tidb race test log job

docs-cn/merge.yaml, docs-dm/merge.yaml, docs/merge.yaml
Release v5.3 PDF for docs/docs-cn/dm.
@TomShawn DON'T merge until v5.3 released.
=> chore: add new version for PDF generation

ticdc/verify.yaml
=> ticdc: add gosec

tiem/verify.yaml
* tiem turn on feishu notify if verify-ci failed, pr owner and ci trigger will receive feishu notify
=> tiem: turn on feishu notify

tidb/daily.yaml
* add all integration test to daily-ci config
=> tidb ci: add integration test task to daily-ci

tiem/verify.yaml
=> tiem: update build image

tidb/daily.yaml
=> feat: tidb daily ci add tcms test

tidb/daily.yaml
=> tidb: add some receivers

tidb/daily.yaml
=> tidb dailyci add ut codecov

tispark/daily.yaml
=> tispark:add daily

dbaas-docs/dbaas-docs-merge-pipeline.yaml, dm/dm-verify-pipeline.yaml, docs-appdev/docs-appdev-merge-pipeline.yaml, docs-cn/docs-cn-merge-pipeline.yaml, docs-cn/docs-cn-verify-pipeline.yaml, docs-dm/docs-dm-merge-pipeline.yaml, docs-tidb-operator/docs-tidb-operator-merge-pipeline.yaml, docs/docs-merge-pipeline.yaml, docs/docs-verify-pipeline.yaml, parser/parser-verify-pipeline.yaml, pd/pd-verify-pipeline.yaml, tidb/tidb-daily-pipeline.yaml, tidb/tidb-verify-pipeline.yaml, tiem/tiem-verify-pipeline.yaml, tiflow/tiflow-verify-pipeline.yaml, tispark/tispark-daily-pipeline.yaml
refactor all config for tipipeline
=> refactor all config for tipipeline

dbaas-docs/dbaas-docs-merge-pipeline.yaml, dm/dm-verify-pipeline.yaml, docs-appdev/docs-appdev-merge-pipeline.yaml, docs-cn/docs-cn-merge-pipeline.yaml, docs-cn/docs-cn-verify-pipeline.yaml, docs-dm/docs-dm-merge-pipeline.yaml, docs-tidb-operator/docs-tidb-operator-merge-pipeline.yaml, docs/docs-merge-pipeline.yaml, docs/docs-verify-pipeline.yaml, parser/parser-verify-pipeline.yaml, pd/pd-verify-pipeline.yaml, tidb/tidb-daily-pipeline.yaml, tidb/tidb-verify-pipeline.yaml, tiem/tiem-verify-pipeline.yaml, tiflow/tiflow-verify-pipeline.yaml, tispark/tispark-daily-pipeline.yaml
=> refactor all config

tispark/tispark-daily-pipeline.yaml
* set it test timeout to 120 min
=> tispark: set it test timeout

docs-cn/docs-cn-merge-pipeline.yaml, docs/docs-merge-pipeline.yaml
Generate PDF on v5.4 (stable)
Do not merge until v5.4 is released.
=> chore: add v5.4  for PDF generation of docs-cn and docs 

tikv-migration/tikv-migration-verify-pipeline.yaml
* tikv-migration add verify ci pipeline
=> tikv-migration: add verify ci pipeline

tikv-migration/tikv-migration-verify-pipeline.yaml
* correct report path
* correct gosec cmds
=> tikv-migration: fix gosec

tikv-migration/tikv-migration-verify-pipeline.yaml
=> gosec: fix report not found

tikv-migration/tikv-migration-verify-pipeline.yaml
=> tikv-migration: add codecov token

tidb/tidb-daily-pipeline.yaml
- run all tidb ut case in daily run
=> run all tidb ut case

tidb/tidb-daily-pipeline.yaml
- increase tidb ut resource usage
=> increase tidb ut resource usage

tidb/tidb-daily-pipeline.yaml
=> update tidb resource usage

tibigdata/tibigdata-daily-pipeline.yaml
=> [WIP]tibigdata:add daily ci

tiflow/tiflow-verify-go1.16-pipeline.yaml, tiflow/tiflow-verify-go1.18-pipeline.yaml
- update tiflow go version to 1.18
=> update tiflow go version to 1.18

tiflow/tiflow-verify-go1.18-pipeline.yaml
- temp remove tiflow gosec check
=> temp remove tiflow gosec check

tidb/tidb-daily-pipeline.yaml, tidb/tidb-verify-pipeline.yaml
- update tidb daily pipeline go version
=> update tidb daily pipeline go version

tiflow/tiflow-verify-go1.16-pipeline.yaml
fix tiflow ut failed on release-5.3
=> fix tiflow ut failed on release-5.3

tiflow/tiflow-verify-go1.16-pipeline.yaml
disable gosec for tiflow for release branch
=> disable gosec for tiflow for release branch

tidb/tidb-tcms-test-pipeline.yaml
exmaple of triggering tcms plans
=> exmaple of triggering tcms plans

tiem/tiem-verify-pipeline.yaml
=> temp offline tiem gosec check

tidb/tidb-daily-pipeline.yaml
* currently ut is unstable, we need to ignore test in unstable.list
* ut / lint / gosec need more CPU and memory resource
* tidb build timeout impore to 20 min
=> fix tidb daily ci failed due to system config

tidb/tidb-daily-pipeline.yaml
* some dailyci not fixed before 20220408, disable those check
=> tmp disable gosec/leak/race

docs-cn/docs-cn-merge-pipeline.yaml, docs/docs-merge-pipeline.yaml
https://ci.pingcap.net/blue/organizations/jenkins/common-check/detail/common-check/37745/pipeline/
```
[2022-05-20T03:20:40.246Z] Binary file media/performance/j-5-cmd.png matches
[2022-05-20T03:20:40.246Z] Binary file media/performance/j-6-cmd.png matches
[2022-05-20T03:20:40.246Z] Binary file media/performance/j-3-cmd.png matches
[2022-05-20T03:20:40.246Z] + exit 1
script returned exit code 1
```
fyi @Oreoxmt
=> refine ci check

tidb/tidb-daily-pipeline.yaml
* add new checker: chain-bench check
=> tidb: add chain bench check to daily ci

tikv-migration/tikv-migration-verify-pipeline.yaml
Signed-off-by: pingyu <yuping@pingcap.com>
1. Change to go1.18.
2. Add release branch named as `cdc-xxx`.
3. Remove other CI tasks using Github action.
=> tikv-migration: Change to go1.18

tikv-migration/tikv-migration-verify-pipeline.yaml
Signed-off-by: zeminzhou <zhouzemin@pingcap.com>
=> add tikv-migration integration test 

docs-cn/docs-cn-merge-pipeline.yaml, docs/docs-merge-pipeline.yaml
fix pdf build failure caused by oom
=> update resources for pdf pipeline

docs-cn/docs-cn-verify-pipeline.yaml
Same as https://github.com/PingCAP-QE/devops-config/pull/150
=> fix: fix git ownership error

docs-cn/docs-cn-merge-pipeline.yaml, docs/docs-merge-pipeline.yaml
add release-7.6 for TiDB Documentation PDF build
=> docs: add release-7.6 for PDF build

docs-tidb-operator/docs-tidb-operator-merge-pipeline.yaml
=> add 1.6 version for docs-tidb-operator pdf
